### ISSUE TITLE
测试翻译机器人

### ISSUE THREAD

**Issue by oeyoews** [oeyoews/neotw#36]

**Comment by tomzcn** [comment]
翻译这个？来自tomzheng

**Comment by tomzcn** [comment]
这是谁家的翻译？微软家？

**Comment by oeyoews** [comment]
github actions 

> 这是谁家的翻译？微软家？

google-translate-api

**Comment by oeyoews** [comment]
github actions 

> 这是谁家的翻译？微软家？

google-translate-api

**Comment by tomzcn** [comment]
> github actions
> 
> > 这是谁家的翻译？微软家？
> 
> google-translate-api

收到。
